config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'

  # ... new
  post 'dashboard/control'
  get 'build_finishes/index', as: 'build_finishes'

  get "home/welcome", :as => :welcome
  get 'home/index'

  root :to => "home#index"

  devise_for :users

	mount Blazer::Engine, at: "/blazer"

	require 'sidekiq/web'
	mount Sidekiq::Web => '/sidekiq'

  # Chartkick Dashboards for AJAX
  get 'dashboard/three_line', as: 'dashboard_three_line'
  get 'dashboard/brand_column', as: 'dashboard_brand_column'
  get 'dashboard/scrape_count', as: 'dashboard_scrape_count'
  get 'dashboard/price_popup/:sku', to: 'dashboard#price_popup', as: 'dashboard_price_popup'

  get 'prices/index', as: 'prices'

  # Uploads Routes
  resources :uploads

end

app/models/build_finish.rb
class BuildFinish < ActiveRecord::Base
  def self.to_csv
    attributes = BuildFinish.attribute_names

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map { |attr| user.send(attr) }
      end
    end
  end
end

app/models/concerns/prices.rb
class Price < ActiveRecord::Base
end

app/models/price.rb
class Price < ActiveRecord::Base
  def self.to_csv
    attributes = Price.attribute_names
    # attributes = %w[brand sku title price site_name quantity]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map { |attr| user.send(attr) }
      end
    end
  end
end

app/models/sku_url.rb
class SkuUrl < ActiveRecord::Base
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  has_attached_file :csv_file
  do_not_validate_attachment_file_type :csv_file

  def initialize(params = {})
    file = params.delete(:file)

    super

    return if !file

    # self.filename = File.basename(file.original_filename)
    # self.content_type = file.content_type
    # self.file_contents = file.read

    # self.filename = File.basename(file.original_filename)
    # self.content_type = file.content_type
    self.csv_file_contents = file.read

    # Why start at 1? To exclude the field titles row.
    CSV.parse(csv_file_contents)[1..-1].each do |row|
      SkuUrl.create!(manuf: row.first, sku: row.last)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/build_finishes_controller.rb
class BuildFinishesController < ApplicationController
  def index
    respond_to do |format|
      format.csv do
        send_data(
        	BuildFinish.all.to_csv,
        	filename: "build-finishes-#{Time.zone.today}.csv"
        )
      end
    end
  end

	def new
		@build_finish = BuildFinish.new
	end

	def create
		@build_finish = BuildFinish.new build_finish_params.slice(*BuildFinish.column_names)
		# @build_finish.attributes = hash.reject{|k,v| !@build_finish.attributes.keys.member?(k.to_s) }
		if @build_finish.save
			redirect_to :root
		else
			render :action => 'new'
		end
	end

	private

	def build_finish_params
		params.require(:build_finish).permit(:application, :productCompositeId, :manufacturer, :productId, :selectedFinish, :freeShippingMessage, :leadTimeMessage, :name, :masterFinish, :uniqueId, :msrp, :price, :consumerPrice, :sku, :title, :slug, :familyLink, :productLink, :savings, :stock, :swatchStyles, :swatchImage, :hideStock)
		params.require(:build_finish).permit(:friendlyStatus, :stockMessage, :isOutOfStock, :isMadeToOrder, :isPreOrder, :status, :savingsFromConsumerPrice, :image100x100, :image220x220, :isPaint, :images_defaultImg, :sale_productSaleId, :sale_catchLine, :sale_saleDetail, :sale_startDate, :sale_endDate, :savingsDetails_standard, :savingsDetails_total, :savingsDetails_percentage, :type_of)
	end


end

app/controllers/dashboard_controller.rb
require 'rake'

class DashboardController < ApplicationController
  before_action :authenticate_user!, only: :show

  def show
    @upload = Upload.new
  end

  def control
    nuke = dashboard_params[:nuke].presence
    search_skus = dashboard_params[:search_skus].presence
    scrape = dashboard_params[:scrape].presence

    if nuke
      SkuUrl.delete_all
      Price.delete_all
      BuildFinish.delete_all
      redirect_to dashboard_show_path
      return
    end

    Rails.application.load_tasks

    %i[search_skus scrape].each { |tk| Rake::Task[tk].reenable }

    if search_skus
      Rake::Task[:search_skus].invoke
      redirect_to dashboard_show_path
      return
    end

    Rake::Task[:scrape].invoke if scrape

    redirect_to dashboard_show_path
  end

  # Dashboard for AJAX (also add route)
  def three_line
    render json: Price.where("sku in ('RP84382RB','5600-3-AMB','5600-3-01')").group(:sku).group_by_day(:created_at).average(:price).chart_json
  end
  def brand_column
    render json: Price.group(:brand).count
  end
  def scrape_count
    render json: Price.group_by_day(:created_at).count
  end
  def price_popup
    find_sku = params[:sku].to_s
    render json: Price.where("sku in ('#{find_sku}')").group(:sku).group_by_day(:created_at).average(:price).chart_json
  end

  private

  def dashboard_params
    params.require(:dashboard).permit(:nuke, :search_skus, :scrape)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end

  def index
    if user_signed_in?

        # was there a previous error msg carry over? make sure it shows in flasher
      flash[:notice] = flash[:error] unless flash[:error].blank?
      redirect_to(  welcome_path()  )

    else

      if flash[:notice].blank?
        flash[:notice] = "sign in if your organization has an account"
      end

    end   # if logged in .. else first time
  end
end

app/controllers/price_controller.rb
class PriceController < ApplicationController

  def index
    respond_to do |format|
      format.html
      format.json { render json: UserDatatable.new(view_context) }
    end
  end

end

app/controllers/prices_controller.rb
class PricesController < ApplicationController

  def index
    respond_to do |format|
      format.html
      format.json { render json: PriceDatatable.new(view_context) }
      format.csv do
        send_data Price.all.to_csv, filename: "prices-#{Time.zone.today}.csv"
      end
    end
  end

end

app/controllers/sku_urls_controller.rb
class SkuUrlsController < ApplicationController
	def new
		@sku_url = SkuUrl.new
	end

	def create
		@sku_url = SkuUrl.new sku_url_params
		# @sku_url.attributes = hash.reject{|k,v| !@sku_url.attributes.keys.member?(k.to_s) }
		if @sku_url.save
			redirect_to :root
		else
			render :action => 'new'
		end
	end

	private

	def sku_url_params
		params.require(:sku_url).permit(:manuf, :sku, :url)
	end


end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.new upload_params
    if @upload.save
      redirect_to dashboard_show_path
      # redirect_to root_path
    else
      render :action => 'new'
    end

    path_to_s3 = 'https:' + @upload.csv_file.url

    # TODO NEXT: Parse through CSV file and save to SkuUrl
    # CSV.new(open(path_to_s3)).each do |row|
    #   SkuUrl.create(manuf: row[0], sku: row[1])
    # end

  end

	private

	def upload_params
    params.require(:upload).permit(:file)
		# params.require(:upload).permit(:csv_file, :user_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/build_finishes_helper.rb
module BuildFinishesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/price_helper.rb
module PriceHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/dashboard/_control.html.erb
<%= link_to 'Search SKUs',
      dashboard_control_path(dashboard: { search_skus: 1}),
      method: :create,
      class: 'btn btn-default',
      style: 'color: black;'
%>

<%= link_to 'Scrape',
      dashboard_control_path(dashboard: { scrape: 1}),
      method: :create,
      class: 'btn btn-primary',
      style: 'color: white;'
%>

<%= link_to 'Nuke All Data!',
      dashboard_control_path(dashboard: { nuke: 1}),
      method: :create,
      class: 'btn btn-danger',
      style: 'color: white;'
%>

<hr />

<%= link_to 'Export Price Data as CSV',
      prices_path(format: :csv),
      class: 'btn btn-default',
      style: 'color: black;'
%>

<%= link_to 'Export Build Data as CSV',
      build_finishes_path(format: :csv),
      class: 'btn btn-default',
      style: 'color: black;'
%>

app/views/dashboard/_upload_not_haml.html.erb
<%= form_for @upload, class: 'form-horizontal' do |f| %>

  <div class="form-group">
    <%= f.label :file, class: 'btn btn-default control-label' do %>
      <%= f.file_field :file, class: 'btn form-control',
        style: 'display:none;',
        onchange: '$("#upload-file-info").html(this.files[0].name)'
      %>
      Choose Manufacturer/SKU CSV File
    <% end -%>

    <span class='label label-warning' id="upload-file-info"></span>
  </div>

  <%= f.submit 'Upload', class: 'btn btn-primary' %>
<% end %>

app/views/dashboard/show.html.haml
%link{:rel => :stylesheet, :type => :"text/css", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"}
%link{:rel => :stylesheet, :type => :"text/css", :href => "https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css"}

= render 'upload_not_haml'
%br

= render 'control'
%hr

%table#prices-table{"data-source" => prices_path(format: :json), :class => "table table-striped table-bordered", :cellspacing => "0", :width => "100%"}
  %thead
    %tr
      %th Brand
      %th SKU
      -# %th Title
      -# %th Price
      %th Average Price
%tbody

%div#popup_chart_container

-# http://chartkick.com/ for documentation, the paths are to use AJAX
= line_chart dashboard_three_line_path

= column_chart dashboard_brand_column_path

= line_chart dashboard_scrape_count_path

= line_chart dashboard_price_popup_path('RP84382RB'), width: "210px", height: "90px"

%table{:style => "width:100%", :class => "dashboard"}
  %tr
    %th Brand
    %th SKU
    %th Title
    %th Price
  - BuildFinish.distinct(:sku).limit(10).each do |b|
    %tr
      %td= b.manufacturer
      %td.sku
        %a
          .popup_chart= line_chart dashboard_price_popup_path(b.sku), width: "420px", height: "180px"
          = b.sku
      %td= link_to b.title, 'https://www.build.com' + b.productLink, target: :_blank
      %td= number_to_currency(b.price)

app/views/home/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/home/index.html.haml
%h1 Home

app/views/home/show.html.haml
#block-text.block
  .content
    %h2.title Home
    .inner
      %p.first
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        = succeed "," do
          %span.hightlight Excepteur sint occaecat cupidatat non proident
      %p
        %span.small Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
      %p
        %span.gray Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
      %hr/
      %p
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        = succeed "," do
          %span.hightlight Excepteur sint occaecat cupidatat non proident
- content_for :sidebar, render(:partial => 'sidebar')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BuildIntel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= @org_name
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tag
  %body
    #container
      #header
        %h1
          = link_to @org_name, "Competitor Pricing"
        #user-navigation
          %ul.wat-cf
            %li
              %a{:href => "#"}= t("web-app-theme.profile", :default => "Profile")
            %li
              %a{:href => "#"}= t("web-app-theme.settings", :default => "Settings")
            %li
              - if user_signed_in?
                = link_to current_user.email, "mailto:#{current_user.email}"
              - else
                = link_to( t("web-app-theme.signup", :default => "Sign up"), new_user_registration_path )
            %li
              - if user_signed_in?
                = link_to( t("web-app-theme.logout", :default => "Sign out"), destroy_user_session_path, :method => :delete )
              - else
                = link_to( t("web-app-theme.login", :default => "Sign in"), new_user_session_path )
        #main-navigation
          %ul.wat-cf
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
          - flash.clear
        #main
          = yield
          #footer
        #sidebar
          = yield :sidebar

app/views/layouts/sign.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Competitor Pricing
    = stylesheet_link_tag "application"
    = csrf_meta_tag
  %body
    #container
      #box
        = yield

app/views/uploads/new.html.haml
= form_for(@upload, multipart: true) do |f|
  %input{:name => "upload[user_id]", :type => "hidden", :value => current_user.id}
  .field
    = f.label :csv_file
    = f.file_field :csv_file
  .actions
    = f.submit 'Upload'